---
# Homestead Architect - PROD Environment Stack
# Docker Swarm stack for production deployment with Portainer
# Usage: docker stack deploy -c stack.prod.yml homestead-architect-prod

version: "3.8"

services:
  frontend:
    image: ${PROD_IMAGE:-homestead-architect-prod:latest}
    env_file:
      - ./.env.prod
    ports:
      - "${PROD_WEB_PORT:-8080}:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - homestead-network
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s

networks:
  homestead-network:
    driver: overlay
    attachable: true