---
# Homestead Architect - DEV Environment Stack
# Docker Swarm stack for local development with Portainer
# Usage: docker stack deploy -c stack.dev.yml homestead-architect-dev

version: "3.8"

services:
  frontend:
    image: ${DEV_IMAGE:-homestead-architect-dev:latest}
    env_file:
      - .env.dev
    ports:
      - "${DEV_WEB_PORT:-8081}:5173"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - homestead-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Optional development database (if not using external Supabase)
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-homestead_dev}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - homestead-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Optional PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env.dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@homestead.local}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - homestead-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  homestead-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  node_modules:
    driver: local
  pgadmin_data:
    driver: local